# -*- coding: utf-8 -*-
"""app2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r6x35rs018NIN1hipvZ_XfztLMKe_EIC
"""



import streamlit as st
import os

# Title of the web app
st.title("Welcome to My Interactive Website")

# Ask for user input (name)
user_name = st.text_input("What's your name?")

# If a name is provided, display a greeting
os.system ('cls')
if user_name:
    st.write(f"Hello, {user_name}! Thanks for visiting this website.")
else:
    st.write("Please enter your name above.")

